/**
 * @file UploadASplatScene.tsx
 * @desc Component that is used to render a uploaded .splat file in a 3D scene.
 * Should really only be used for debugging/allowing a user to render .splat files 
 * from their local machine and/or generated by other tools
 */

import React, { useState } from 'react';
import { Container, Row, Col, Card, Form, Button, Alert } from 'react-bootstrap';
import NavBar from '../../NavbarLink/NavbarLink';
import Footer from '../../Footer/Footer';
import SplatCloudHandler from '../OutputHandlers/SplatCloud/SplatCloudHandler';

const UploadASplatScene: React.FC = () => {
  const [splatFile, setSplatFile] = useState<File | null>(null);
  const [splatData, setSplatData] = useState<Uint8Array | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      setSplatFile(event.target.files[0]);
      setError(null);
    }
  };

  const handleUpload = () => {
    if (splatFile) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const result = e.target?.result;
        if (result instanceof ArrayBuffer) {
          setSplatData(new Uint8Array(result));
        }
      };
      reader.onerror = () => {
        setError('Failed to read the file. Please try again.');
      };
      reader.readAsArrayBuffer(splatFile);
    } else {
      setError('Please select a .splat file first.');
    }
  };

  return (
    <div className="d-flex flex-column min-vh-100">
      <NavBar />
      <Container fluid className="flex-grow-1 py-3">
        <Row className="justify-content-center">
          <Col xs={12} md={10} lg={8}>
            <Card>
              <Card.Body>
                <Card.Title as="h2" className="mb-4 text-dark">Upload Splat Scene</Card.Title>
                {error && <Alert variant="danger">{error}</Alert>}
                <Form>
                  <Form.Group controlId="splatFile" className="mb-3">
                    <Form.Label>Choose a .splat file</Form.Label>
                    <Form.Control 
                      type="file" 
                      onChange={handleFileChange}
                      accept=".splat"
                    />
                  </Form.Group>
                  {/*@ts-ignore*/}
                  <Button 
                    variant="primary" 
                    onClick={handleUpload}
                    disabled={!splatFile}
                  >
                    Upload and View
                  </Button>
                </Form>
                {splatData && (
                  <div className="mt-4">
                    <h3>Splat Cloud Viewer</h3>
                    <div style={{ height: '500px', width: '100%' }}>
                      <SplatCloudHandler data={splatData} />
                    </div>
                  </div>
                )}
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </Container>
      <Footer />
    </div>
  );
};

export default UploadASplatScene;